collisionscount = 0
collisionsoriginal = 0
crashescount = 0
crashesfatalities = 0
crashesoriginal = 179268
partiescount = 0
partiesfatalities = 0
partiesoriginal = 386281
prjdateus = "06/30/2025"
prjdatewhole = "06/30/2025"
prjmonths = 162
prjupdated = "December 11, 2025"
prjversion = 2025.02
victimscount = 0
victimsfatalities = 0
victimsoriginal = 310432
