[2012]
dateend = "2012-12-31"
dategp = "2025-11-05"
datestart = "2012-01-01"
dateupdated = "2025-01-30"
notes = "Data removed from TIMS (updated on December 2025)"
status = "final"
year = 2012

    [2012.excluded]
    crashes = 188
    parties = 367
    victims = 305

    [2012.files]
    crashes = "Crashes_2012.csv"
    parties = "Parties_2012.csv"
    victims = "Victims_2012.csv"

    [2012.geocoded]
    crashes = 13989
    parties = 30123
    victims = 27178

    [2012.reported]
    crashes = 14177
    parties = 30490
    victims = 27483

[2013]
dateend = "2013-12-31"
dategp = "2025-11-05"
datestart = "2013-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2013

    [2013.excluded]
    crashes = 191
    parties = 377
    victims = 327

    [2013.files]
    crashes = "Crashes_2013.csv"
    parties = "Parties_2013.csv"
    victims = "Victims_2013.csv"

    [2013.geocoded]
    crashes = 13811
    parties = 29845
    victims = 26435

    [2013.reported]
    crashes = 14002
    parties = 30222
    victims = 26762

[2014]
dateend = "2014-12-31"
dategp = "2025-11-05"
datestart = "2014-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2014

    [2014.excluded]
    crashes = 153
    parties = 301
    victims = 258

    [2014.files]
    crashes = "Crashes_2014.csv"
    parties = "Parties_2014.csv"
    victims = "Victims_2014.csv"

    [2014.geocoded]
    crashes = 13748
    parties = 29747
    victims = 26688

    [2014.reported]
    crashes = 13901
    parties = 30048
    victims = 26946

[2015]
dateend = "2015-12-31"
dategp = "2025-11-05"
datestart = "2015-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2015

    [2015.excluded]
    crashes = 172
    parties = 338
    victims = 308

    [2015.files]
    crashes = "Crashes_2015.csv"
    parties = "Parties_2015.csv"
    victims = "Victims_2015.csv"

    [2015.geocoded]
    crashes = 14727
    parties = 32134
    victims = 28988

    [2015.reported]
    crashes = 14899
    parties = 32472
    victims = 29296

[2016]
dateend = "2016-12-31"
dategp = "2025-11-05"
datestart = "2016-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2016

    [2016.excluded]
    crashes = 342
    parties = 723
    victims = 652

    [2016.files]
    crashes = "Crashes_2016.csv"
    parties = "Parties_2016.csv"
    victims = "Victims_2016.csv"

    [2016.geocoded]
    crashes = 15712
    parties = 34413
    victims = 30242

    [2016.reported]
    crashes = 16054
    parties = 35136
    victims = 30894

[2017]
dateend = "2017-12-31"
dategp = "2025-11-05"
datestart = "2017-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2017

    [2017.excluded]
    crashes = 292
    parties = 625
    victims = 418

    [2017.files]
    crashes = "Crashes_2017.csv"
    parties = "Parties_2017.csv"
    victims = "Victims_2017.csv"

    [2017.geocoded]
    crashes = 15078
    parties = 32890
    victims = 26126

    [2017.reported]
    crashes = 15370
    parties = 33515
    victims = 26544

[2018]
dateend = "2018-12-31"
dategp = "2025-11-05"
datestart = "2018-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2018

    [2018.excluded]
    crashes = 280
    parties = 629
    victims = 415

    [2018.files]
    crashes = "Crashes_2018.csv"
    parties = "Parties_2018.csv"
    victims = "Victims_2018.csv"

    [2018.geocoded]
    crashes = 13688
    parties = 29950
    victims = 23756

    [2018.reported]
    crashes = 13968
    parties = 30579
    victims = 24171

[2019]
dateend = "2019-12-31"
dategp = "2025-11-05"
datestart = "2019-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2019

    [2019.excluded]
    crashes = 326
    parties = 690
    victims = 490

    [2019.files]
    crashes = "Crashes_2019.csv"
    parties = "Parties_2019.csv"
    victims = "Victims_2019.csv"

    [2019.geocoded]
    crashes = 12068
    parties = 26405
    victims = 20646

    [2019.reported]
    crashes = 12394
    parties = 27095
    victims = 21136

[2020]
dateend = "2020-12-31"
dategp = "2025-11-05"
datestart = "2020-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2020

    [2020.excluded]
    crashes = 296
    parties = 620
    victims = 463

    [2020.files]
    crashes = "Crashes_2020.csv"
    parties = "Parties_2020.csv"
    victims = "Victims_2020.csv"

    [2020.geocoded]
    crashes = 8719
    parties = 18469
    victims = 14044

    [2020.reported]
    crashes = 9015
    parties = 19089
    victims = 14507

[2021]
dateend = "2021-12-31"
dategp = "2025-11-05"
datestart = "2021-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2021

    [2021.excluded]
    crashes = 263
    parties = 505
    victims = 369

    [2021.files]
    crashes = "Crashes_2021.csv"
    parties = "Parties_2021.csv"
    victims = "Victims_2021.csv"

    [2021.geocoded]
    crashes = 11939
    parties = 25421
    victims = 18283

    [2021.reported]
    crashes = 12202
    parties = 25926
    victims = 18652

[2022]
dateend = "2022-12-31"
dategp = "2025-11-05"
datestart = "2022-01-01"
dateupdated = "2025-06-12"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2022

    [2022.excluded]
    crashes = 305
    parties = 600
    victims = 457

    [2022.files]
    crashes = "Crashes_2022.csv"
    parties = "Parties_2022.csv"
    victims = "Victims_2022.csv"

    [2022.geocoded]
    crashes = 12298
    parties = 26190
    victims = 18455

    [2022.reported]
    crashes = 12603
    parties = 26790
    victims = 18912

[2023]
dateend = "2023-12-31"
dategp = "2025-11-05"
datestart = "2023-01-01"
dateupdated = "2025-09-30"
notes = "Final data in TIMS (updated on December 2025)"
status = "final"
year = 2023

    [2023.excluded]
    crashes = 329
    parties = 673
    victims = 484

    [2023.files]
    crashes = "Crashes_2023.csv"
    parties = "Parties_2023.csv"
    victims = "Victims_2023.csv"

    [2023.geocoded]
    crashes = 12350
    parties = 26182
    victims = 18279

    [2023.reported]
    crashes = 12679
    parties = 26855
    victims = 18763

[2024]
dateend = "2024-12-31"
dategp = "2025-11-05"
datestart = "2024-01-01"
dateupdated = "2025-09-30"
notes = "Provisional data in TIMS (updated on December 2025)"
status = "provisional"
year = 2024

    [2024.excluded]
    crashes = 314
    parties = 602
    victims = 464

    [2024.files]
    crashes = "Crashes_2024.csv"
    parties = "Parties_2024.csv"
    victims = "Victims_2024.csv"

    [2024.geocoded]
    crashes = 12239
    parties = 25985
    victims = 17980

    [2024.reported]
    crashes = 12553
    parties = 26587
    victims = 18444

[2025]
dateend = "2025-06-30"
dategp = "2025-11-05"
datestart = "2025-01-01"
dateupdated = "2025-09-30"
notes = "Provisional data in TIMS (updated on December 2025)"
status = "provisional"
year = 2025

    [2025.excluded]
    crashes = 170
    parties = 333
    victims = 246

    [2025.files]
    crashes = "Crashes_2025.csv"
    parties = "Parties_2025.csv"
    victims = "Victims_2025.csv"

    [2025.geocoded]
    crashes = 5281
    parties = 11144
    victims = 7676

    [2025.reported]
    crashes = 5451
    parties = 11477
    victims = 7922
