crashes_ind = {0: "No", 1: "Yes"}
parties_ind = {0: "No", 1: "Yes"}
victims_ind = {0: "No", 1: "Yes"}
combined_ind = {
    1: "crashes only",
    2: "parties only",
    3: "victims only",
    4: "parties with victims",
    5: "crashes with victims, no parties",
    6: "crashes with parties, no victims",
    7: "crashes with parties and victims",
}
place_type = {1: "City", 2: "Unincorporated"}
dt_quarter = {1: "Q1", 2: "Q2", 3: "Q3", 4: "Q4"}
dt_month = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December",
}
dt_week_day = {
    1: "Sunday",
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday",
    7: "Saturday",
}
dt_dst = {0: "No", 1: "Yes"}
dt_zone = {-8: "PST", -7: "PDT"}
coll_time_intervals = {
    1: "Night (00:00am to 06:00am)",
    2: "Morning (06:00am to 12:00pm)",
    3: "Afternoon (12:00pm to 18:00pm)",
    4: "Evening (18:00pm to 00:00am)",
    9: "Unknown Time",
}
rush_hours = {
    0: "Non-Rush Hours",
    1: "Morning (6-9am)",
    2: "Evening (4-7pm)",
    9: "Unknown Time",
}
rush_hours_bin = {0: "Non-Rush Hours", 1: "Rush Hours"}
coll_severity = {
    0: "No injury",
    1: "Possible injury or pain",
    2: "Minor or visible injury",
    3: "Serious or severe injury",
    4: "Fatal injury",
}
coll_severity_bin = {0: "None, minor or pain", 1: "Severe or fatal"}
coll_severity_rank = {
    0: "None or Minor Injuries",
    1: "Single Injury (Severe)",
    2: "Multiple Injuries (Severe)",
    3: "Single Fatality, No Injuries (Fatal)",
    4: "Single Fatality, Single Injury (Fatal)",
    5: "Single Fatality, Multiple Injuries (Fatal)",
    6: "Multiple Fatalities, No Injuries (Fatal)",
    7: "Multiple Fatalities, Single Injury (Fatal)",
    8: "Multiple Fatalities, Multiple Injuries (Fatal)",
}
ind_severe = {0: "Not a severe injury", 1: "Severe injury"}
ind_fatal = {0: "Not a fatal injury", 1: "Fatal injury"}
ind_multi = {0: "Single injury or fatality", 1: "Multiple injuries or fatalities"}
primary_coll_factor = {
    1: "(Vehicle) Code Violation",
    2: "Other Improper Driving",
    3: "Other Than Driver",
    4: "Unknown",
    5: "Fell Asleep",
    0: "Not Stated",
}
type_of_coll = {
    1: "Head-On",
    2: "Sideswipe",
    3: "Rear End",
    4: "Broadside",
    5: "Hit Object",
    6: "Overturned",
    7: "Vehicle/ Pedestrian",
    8: "Other",
    0: "Not Stated",
}
ped_accident = {0: "No", 1: "Yes"}
bic_accident = {0: "No", 1: "Yes"}
mc_accident = {0: "No", 1: "Yes"}
truck_accident = {0: "No", 1: "Yes"}
hit_and_run = {0: "Not Hit and Run", 1: "Misdemeanor", 2: "Felony"}
hit_and_run_bin = {0: "No", 1: "Yes"}
alcohol_involved = {0: "No", 1: "Yes"}
chp_shift = {
    1: "06:00 thru 13:59",
    2: "14:00 thru 21:59",
    3: "22:00 thru 05:59",
    4: "CHP Not Stated",
    5: "Not CHP",
}
special_cond = {
    1: "Schoolbus on Public Roadway",
    2: "State University (Also SFIA)",
    3: "Schoolbus Not on Public Roadway",
    4: "Offroad (Unimproved)",
    5: "Vista Point or Rest Area or Sales or Inspection Facility",
    6: "Other Public Access (Improved)",
    0: "Not Above",
    9: "Not Stated",
}
beat_type = {
    1: "CHP State Highway",
    2: "CHP County RoadLine",
    3: "CHP County RoadArea",
    4: "Schoolbus on City Roadway",
    5: "Schoolbus not on Public Roadway",
    6: "Offroad (Unimproved)",
    7: "Vista Point or Rest Area or Scales or Inspection Facility",
    8: "Other Public Access (Improved)",
    0: "Not CHP",
}
chp_beat_type = {
    1: "Interstate",
    2: "US Highway",
    3: "State Route",
    4: "County RoadLine",
    5: "County RoadArea",
    6: "Safety Services Program Beats",
    7: "Administrative Beats (900's)",
    8: "Contract City: US Highway",
    9: "Contract City: State Route",
    10: "Contract City: County RoadLine",
    11: "Contract City: County RoadArea",
    0: "Not CHP",
}
chp_beat_class = {1: "CHP Primary", 2: "CHP Other", 0: "Not CHP"}
direction = {1: "North", 2: "South", 3: "East", 4: "West", 0: "Not Stated"}
intersection = {0: "No", 1: "Yes"}
weather_1 = {
    1: "Clear",
    2: "Cloudy",
    3: "Raining",
    4: "Snowing",
    5: "Fog",
    6: "Wind",
    7: "Other",
    0: "Not Stated",
}
weather_2 = {
    1: "Clear",
    2: "Cloudy",
    3: "Wind",
    4: "Raining",
    5: "Fog",
    6: "Snowing",
    7: "Other",
    0: "Not Stated",
}
weather_comb = {
    10: "Clear",
    12: "Clear and Cloudy",
    13: "Clear and Wind",
    14: "Clear and Raining",
    15: "Clear and Fog",
    16: "Clear and Snowing",
    17: "Clear and Other",
    20: "Cloudy",
    21: "Cloudy and Clear",
    23: "Cloudy and Wind",
    24: "Cloudy and Raining",
    25: "Cloudy and Fog",
    26: "cloudy and Snowing",
    27: "Cloudy and Other",
    30: "Wind",
    31: "Wind and Clear",
    32: "Wind and Cloudy",
    34: "Wind and Raining",
    35: "Wind and Fog",
    36: "Wind and Snowing",
    37: "Wind and Other",
    40: "Raining",
    41: "Raining and Clear",
    42: "Raining and Cloudy",
    43: "Raining and Wind",
    45: "Raining and Fog",
    46: "Raining and Snowing",
    47: "Raining and Other",
    50: "Fog",
    51: "Fog and Clear",
    52: "Fog and Cloudy",
    53: "Fog and Wind",
    54: "Fog and Raining",
    56: "Fog and Snowing",
    57: "Fog and Other",
    60: "Snowing",
    61: "Snowing and Clear",
    62: "Snowing and Cloudy",
    63: "Snowing and Wind",
    64: "Snowing and Raining",
    65: "Snowing and Fog",
    67: "Snowing and Other",
    70: "Other",
    71: "Other and Clear",
    72: "Other and Cloudy",
    73: "Other and Wind",
    74: "Other and Raining",
    75: "Other and Fog",
    76: "Other and Snowing",
    0: "Not Stated",
}
road_surface = {
    1: "Dry",
    2: "Wet",
    3: "Snowy or Icy",
    4: "Slippery (Muddy, Oily, etc)",
    5: "Unknown",
    0: "Not Stated",
}
road_cond_1 = {
    1: "Holes, Deep Ruts",
    2: "Loose Material on Roadway",
    3: "Obstruction on Roadway",
    4: "Construction or Repair Zone",
    5: "Reduced Roadway Width",
    6: "Flooded",
    7: "Other",
    8: "No Unusual Condition",
    0: "Not Stated",
}
road_cond_2 = {
    1: "Holes, Deep Ruts",
    2: "Loose Material on Roadway",
    3: "Obstruction on Roadway",
    4: "Construction or Repair Zone",
    5: "Reduced Roadway Width",
    6: "Flooded",
    7: "Other",
    8: "No Unusual Condition",
    0: "Not Stated",
}
lighting = {
    0: "Not Stated",
    1: "Daylight",
    2: "Dusk - Dawn",
    3: "Dark - Street Lights",
    4: "Dark - No Street Lights",
    5: "Dark - Street Lights Not Functioning",
}
control_device = {
    1: "Functioning",
    2: "Not Functioning",
    3: "Obscured",
    4: "None",
    0: "Not Stated",
}
state_hwy_ind = {0: "Not State Highway", 1: "State Highway"}
side_of_hwy = {
    1: "Northbound",
    2: "Southbound",
    3: "Eastbound",
    4: "Westbound",
    5: "Left",
    6: "Right",
    0: "Not Stated",
}
tow_away = {0: "No", 1: "Yes"}
pcf_code_of_viol = {
    1: "Business and Professions",
    2: "Vehicle",
    3: "City Health and Safety",
    4: "City Ordinance",
    5: "County Ordinance",
    6: "Penal",
    7: "Streets and Highways",
    8: "Welfare and Institutions",
    0: "Not Stated",
}
pcf_viol_category = {
    1: "Driving or Bicycling Under the Influence of Alcohol or Drug",
    2: "Impeding Traffic",
    3: "Unsafe Speed",
    4: "Following Too Closely",
    5: "Wrong Side of Road",
    6: "Improper Passing",
    7: "Unsafe Lane Change",
    8: "Improper Turning",
    9: "Automobile Right of Way",
    10: "Pedestrian Right of Way",
    11: "Pedestrian Violation",
    12: "Traffic Signals and Signs",
    13: "Hazardous Parking",
    14: "Lights",
    15: "Brakes",
    16: "Other Equipment",
    17: "Other Hazardous Violation",
    18: "Other Than Driver (or Pedestrian)",
    21: "Unsafe Starting or Backing",
    22: "Other Improper Driving",
    23: "Pedestrian or 'Other' Under the Influence of Alcohol or Drug",
    24: "Fell Asleep",
    0: "Unknown",
    99: "Not Stated",
}
mviw = {
    1: "Non-Collision",
    2: "Pedestrian",
    3: "Other Motor Vehicle",
    4: "Motor Vehicle on Other Roadway",
    5: "Parked Motor Vehicle",
    6: "Train",
    7: "Bicycle",
    8: "Animal",
    9: "Fixed Object",
    10: "Other Object",
    11: "Non-Collision and Additional Object",
    12: "Pedestrian and Additional Object",
    13: "Other Motor Vehicle and Additional Object",
    14: "Motor Vehicle on Other Roadway and Additional Object",
    15: "Parked Motor Vehicle and Additional Object",
    16: "Train and Additional Object",
    17: "Bicycle and Additional Object",
    18: "Animal and Additional Object",
    19: "Fixed Object and Additional Object",
    20: "Other Object and Additional Object",
    0: "Not Stated",
}
ped_action = {
    1: "No Pedestrian Involved",
    2: "Crossing in Crosswalk at Intersection",
    3: "Crossing in Crosswalk Not at Intersection",
    4: "Crossing Not in Crosswalk",
    5: "In Road, Including Shoulder",
    6: "Not in Road",
    7: "Approaching/Leaving School Bus",
    0: "Not Stated",
}
not_private_property = {0: "No", 1: "Yes"}
stwd_veh_type_at_fault = {
    1: "Passenger Car/Station Wagon",
    2: "Passenger Car with Trailer",
    3: "Motorcycle/Scooter",
    4: "Pickup or Panel Truck",
    5: "Pickup or Panel Truck with Trailer",
    6: "Truck or Truck Tractor",
    7: "Truck or Truck Tractor with Trailer",
    8: "Schoolbus",
    9: "Other Bus",
    10: "Emergency Vehicle",
    11: "Highway Construction Equipment",
    12: "Bicycle",
    13: "Other Vehicle",
    14: "Pedestrian",
    15: "Moped",
    0: "Not Stated",
}
chp_veh_type_at_fault = {
    1: "Passenger Car, Station Wagon, or Jeep",
    2: "Motorcycle",
    3: "Motor-Driven Cycle < 15 hp",
    4: "Bicycle",
    5: "Motorized Bicycle",
    6: "All-Terrain Vehicle - ATV",
    7: "Sport Utility Vehicle",
    8: "Minivan",
    9: "Paratransit Bus",
    10: "Tour Bus",
    11: "Other Commercial Bus",
    12: "Non-Commercial Bus",
    13: "Schoolbus Public I",
    14: "Schoolbus Public II",
    15: "Schoolbus Private I",
    16: "Schoolbus Private II",
    17: "Schoolbus Contractual I",
    18: "Schoolbus Contractual II",
    19: "General Public Paratransit Vehicle",
    20: "Public Transit Authority",
    21: "Two-Axle Tank Truck",
    22: "Pickup or Panel Truck",
    23: "Pickup Truck With Camper",
    24: "Three-Axle Tank Truck",
    25: "Truck Tractor",
    26: "Two-Axle Truck",
    27: "Three-Axle Truck",
    28: "Semi-Tank Trailer",
    29: "Pull-Tank Trailer",
    30: "Two-Tank Trailer",
    31: "Semi-Trailer",
    32: "Pull Trailer - includes dolly",
    33: "Two Trailers - includes semi and trailer",
    34: "Boat Trailer",
    35: "Utility Trailer",
    36: "Trailer Coach",
    37: "Oversize Vehicle/Load",
    38: "Pole, Pipe, or Logging Dolly",
    39: "Three Trailers - includes semi and two trailers",
    40: "Semi 48 or Less with King Pin to Trailer Axle of over 38",
    41: "Ambulance",
    42: "Dune Buggy",
    43: "Fire Truck - not rescue",
    44: "Forklift",
    45: "Highway Construction Equipment - only while not in construction area",
    46: "Implement of Husbandry",
    47: "Motor Home (40 ft or less)",
    48: "CHP, Police, or Sheriff Car - emergency service or not",
    49: "CHP, Police, or Sheriff Motorcycle - emergency service or not",
    50: "Mobile Equipment",
    51: "Farm Labor Vehicle - certified",
    52: "Federally Legal Double Cargo Combo over 75 ft",
    53: "5th Wheel Trailer",
    54: "Container Chassis",
    55: "Two-Axle Tow Truck",
    56: "Three-Axle Tow Truck",
    57: "Farm Labor Vehicle (non-certified)",
    58: "Farm Labor Transporter",
    59: "Motorhome - over 40 ft",
    60: "Pedestrian (includes motorized wheelchair)",
    61: "School Pupil Activity Bus I (<2002)",
    62: "School Pupil Activity Bus II (<2002)",
    63: "Youth Bus",
    64: "School Pupil Activity Bus I",
    65: "School Pupil Activity Bus II",
    66: "School Bus Without Pupil Passengers",
    71: "Passenger Car - Hazardous Materials Only",
    72: "Pickups and Panels - Hazardous Materials Only",
    73: "Pickups and Campers - Hazardous Materials Only",
    75: "Truck Tractor - Hazardous Materials Only",
    76: "Two-Axle Truck - Hazardous Materials Only",
    77: "Three or More Axle Truck - Hazardous Materials Only",
    78: "Two-Axle Tank Truck - Hazardous Materials Only",
    79: "Three-Axle Tank Truck - Hazardous Materials Only",
    81: "Passenger Car - Hazardous Waste or Waste/Material Combo",
    82: "Pickups and Panels - Hazardous Waste or Waste/Material Combo",
    83: "Pickups and Campers - Hazardous Waste or Waste/Material Combo",
    85: "Truck Tractor - Hazardous Waste or Waste/Material Combo",
    86: "Two-Axle Truck - Hazardous Waste or Waste/Material Combo",
    87: "Three or More Axle Truck - Hazardous Waste or Waste/Material Combo",
    88: "Two-Axle Tank Truck - Hazardous Waste or Waste/Material Combo",
    89: "Three-Axle Tank Truck - Hazardous Waste or Waste/Material Combo",
    91: "Electric Bicycle",
    93: "Electrically Motorized Board",
    94: "Motorized Transportation Device",
    95: "Miscellaneous Non-Motorized Vehicle With Victim",
    96: "Miscellaneous Motorized Vehicle",
    97: "Low Speed Vehicle",
    98: "Emergency Vehicle on an Emergency Run",
    99: "Not Stated or Unknown - Hit and Run",
}
primary_ramp = {
    1: "To",
    2: "From",
    3: "North off ramp",
    4: "South off ramp",
    5: "East off ramp",
    6: "West off ramp",
    7: "North on ramp",
    8: "South on ramp",
    9: "East on ramp",
    10: "West on ramp",
    11: "Transition",
    12: "Collector",
    13: "Connector",
    0: "Not Stated",
}
secondary_ramp = {
    1: "To",
    2: "From",
    3: "North off ramp",
    4: "South off ramp",
    5: "East off ramp",
    6: "West off ramp",
    7: "North on ramp",
    8: "South on ramp",
    9: "East on ramp",
    10: "West on ramp",
    11: "Transition",
    12: "Collector",
    13: "Connector",
    0: "Not Stated",
}
party_type = {
    1: "Driver (including Hit and Run)",
    2: "Pedestrian",
    3: "Parked Vehicle",
    4: "Bicyclist",
    5: "Other",
    6: "Operator",
    0: "Not Stated",
}
at_fault = {0: "No", 1: "Yes"}
party_sex = {1: "Male", 2: "Female", 3: "Nonbinary", 0: "Not Stated"}
party_age = {998: "Unknown"}
party_age_group = {
    0: "Unknown",
    1: "0-10",
    2: "11-18",
    3: "19-25",
    4: "26-35",
    5: "36-45",
    6: "46-55",
    7: "56-65",
    8: "66-80",
    9: "81-100",
    10: "100+",
}
party_race = {
    1: "Asian",
    2: "Black",
    3: "Hispanic",
    4: "Other",
    5: "White",
    0: "Not Stated",
}
inattention = {
    1: "Cell Phone Handheld",
    2: "Cell Phone Handsfree",
    3: "Electronic Equipment",
    4: "Radio/CD",
    5: "Smoking",
    6: "Eating",
    7: "Children",
    8: "Animal",
    9: "Personal Hygiene",
    10: "Reading",
    11: "Other",
    12: "Cell Phone",
    0: "Not Stated",
}
party_sobriety = {
    1: "Had Not Been Drinking",
    2: "Had Been Drinking, Under Influence",
    3: "Had Been Drinking, Not Under Influence",
    4: "Had Been Drinking, Impairment Unknown",
    5: "Impairment Unknown",
    6: "Not Applicable",
    0: "Not Stated",
}
dui_alcohol_ind = {0: "No", 1: "Yes"}
party_drug_physical = {
    1: "Under Drug Influence",
    2: "Impairment - Physical",
    3: "Impairment Unknown",
    4: "Not Applicable",
    5: "Sleepy/Fatigued",
    0: "Not Stated",
}
dui_drug_ind = {0: "No", 1: "Yes"}
dir_of_travel = {1: "North", 2: "South", 3: "East", 4: "West", 0: "Not Stated"}
party_safety_eq_1 = {
    1: "None in Vehicle",
    2: "Unknown",
    3: "Lap Belt Used",
    4: "Lap Belt Not Used",
    5: "Shoulder Harness Used",
    6: "Shoulder Harness Not Used",
    7: "Lap/Shoulder Harness Used",
    8: "Lap/Shoulder Harness Not Used",
    9: "Passive Restraint Used",
    10: "Passive Restraint Not Used",
    11: "Air Bag Deployed",
    12: "Air Bag Not Deployed",
    13: "Other",
    14: "Not Required",
    15: "Child Restraint in Vehicle Used",
    16: "Child Restraint in Vehicle Not Used",
    17: "Child Restraint in Vehicle, Use Unknown",
    18: "Child Restraint in Vehicle, Improper Use",
    19: "No Child Restraint in Vehicle",
    20: "Driver, Motorcycle Helmet Not Used",
    21: "Driver, Motorcycle Helmet Used",
    22: "Passenger, Motorcycle Helmet Not Used",
    23: "Passenger, Motorcycle Helmet Used",
    0: "Not Stated",
}
party_safety_eq_2 = {
    1: "None in Vehicle",
    2: "Unknown",
    3: "Lap Belt Used",
    4: "Lap Belt Not Used",
    5: "Shoulder Harness Used",
    6: "Shoulder Harness Not Used",
    7: "Lap/Shoulder Harness Used",
    8: "Lap/Shoulder Harness Not Used",
    9: "Passive Restraint Used",
    10: "Passive Restraint Not Used",
    11: "Air Bag Deployed",
    12: "Air Bag Not Deployed",
    13: "Other",
    14: "Not Required",
    15: "Child Restraint in Vehicle Used",
    16: "Child Restraint in Vehicle Not Used",
    17: "Child Restraint in Vehicle, Use Unknown",
    18: "Child Restraint in Vehicle, Improper Use",
    19: "No Child Restraint in Vehicle",
    20: "Driver, Motorcycle Helmet Not Used",
    21: "Driver, Motorcycle Helmet Used",
    22: "Passenger, Motorcycle Helmet Not Used",
    23: "Passenger, Motorcycle Helmet Used",
    0: "Not Stated",
}
finan_respons = {
    0: "No Proof of Insurance Obtained",
    1: "Yes, Proof of Insurance Obtained",
    2: "Not Applicable (parked cars, bicyclists, pedestrians, and party type others)",
    3: "Used if the officer is called away from the scene of the crash prior to obtaining the insurance information",
    9: "Not Stated",
}
sp_info_1 = {1: "Hazardous materials", 0: "Not Stated"}
sp_info_2 = {
    1: "Cell Phone in Use",
    2: "Cell Phone Not in Use",
    3: "No Cell Phone/Unknown",
    4: "Cell Phone Handheld in Use",
    5: "Cell Phone Handsfree in Use",
    6: "Cell Phone Use Unknown",
    0: "Not Stated",
}
sp_info_3 = {1: "School Bus Related", 0: "Not Stated"}
oaf_viol_code = {
    1: "Business and Professions",
    2: "Vehicle",
    3: "City Health and Safety",
    4: "City Ordinance",
    5: "County Ordinance",
    6: "Penal",
    7: "Streets and Highways",
    8: "Welfare and Institutions",
    0: "Not Stated",
}
oaf_viol_cat = {
    0: "Not Stated",
    1: "Under Influence in Public",
    2: "County Ordinance",
    3: "City Ordinance",
    5: "Business/Professions Code",
    6: "Felony Penal Code",
    8: "Controlled Substances (Felony Health and Safety)",
    9: "Health/Safety Code (Misdemeanor)",
    10: "Penal Code (Misdemeanor)",
    11: "Streets/Highways Code",
    13: "Welfare/Institutions Code",
    15: "Manslaughter",
    16: "Non-Vehicle Code Not Specified Above",
    17: "Fish and Game Code",
    18: "Agriculture Code",
    19: "Hit and Run",
    20: "Driving or Bicycling Under the Influence of Alcohol or Drug",
    21: "Improper Lane Change",
    22: "Impeding Traffic",
    23: "Failure to Heed Stop Signal",
    24: "Failure to Heed Stop Sign",
    25: "Unsafe Speed",
    26: "Reckless Driving",
    27: "Wrong Side of Road",
    28: "Unsafe Lane Change",
    29: "Improper Passing",
    30: "Following Too Closely",
    31: "Improper Turning",
    33: "Automobile Right-of-Way",
    34: "Pedestrian Right-of-Way",
    35: "Pedestrian Violation",
    38: "Hazardous Parking",
    39: "Lights",
    40: "Brakes",
    43: "Other Equipment",
    44: "Other Hazardous Movement",
    46: "Improper Registration",
    47: "Other Non-Moving Violation",
    48: "Excessive Smoke",
    49: "Excessive Noise",
    50: "Overweight",
    51: "Oversize",
    52: "Over Maximum Speed",
    53: "Unsafe Starting or Backing",
    60: "Off-Highway Vehicle Violation",
    61: "Child Restraint",
    62: "Seat Belt",
    63: "Seat Belt (Equipment)",
    99: "Unknown",
}
oaf_1 = {
    1: "Violation",
    2: "Vision Obscurements",
    3: "Inattention",
    4: "Stop and Go Traffic",
    5: "Entering/Leaving Ramp",
    6: "Previous Collision",
    7: "Unfamiliar With Road",
    8: "Defective Vehicle Equipment",
    9: "Uninvolved Vehicle",
    10: "Other",
    11: "None Apparent",
    12: "Runaway Vehicle",
    13: "Inattention, Cell Phone",
    14: "Inattention, Electronic Equip.",
    15: "Inattention, Radio/CD",
    16: "Inattention, Smoking",
    17: "Inattention, Eating",
    18: "Inattention, Children",
    19: "Inattention, Animal",
    20: "Inattention, Personal Hygiene",
    21: "Inattention, Reading",
    22: "Inattention, Other",
    0: "Not Stated",
}
oaf_2 = {
    1: "Violation",
    2: "Vision Obscurements",
    3: "Inattention",
    4: "Stop and Go Traffic",
    5: "Entering/Leaving Ramp",
    6: "Previous Collision",
    7: "Unfamiliar With Road",
    8: "Defective Vehicle Equipment",
    9: "Uninvolved Vehicle",
    10: "Other",
    11: "None Apparent",
    12: "Runaway Vehicle",
    13: "Inattention, Cell Phone",
    14: "Inattention, Electronic Equip.",
    15: "Inattention, Radio/CD",
    16: "Inattention, Smoking",
    17: "Inattention, Eating",
    18: "Inattention, Children",
    19: "Inattention, Animal",
    20: "Inattention, Personal Hygiene",
    21: "Inattention, Reading",
    22: "Inattention, Other",
    0: "Not Stated",
}
move_pre_acc = {
    1: "Stopped",
    2: "Proceeding Straight",
    3: "Ran Off Road",
    4: "Making Right Turn",
    5: "Making Left Turn",
    6: "Making U-Turn",
    7: "Backing",
    8: "Slowing/Stopping",
    9: "Passing Other Vehicle",
    10: "Changing Lanes",
    11: "Parking Maneuver",
    12: "Entering Traffic",
    13: "Other Unsafe Turning",
    14: "Crossed Into Opposing Lane",
    15: "Parked",
    16: "Merging",
    17: "Traveling Wrong Way",
    18: "Other",
    19: "Lane Splitting",
    0: "Not Stated",
}
vehicle_year = {9999: "Not Stated"}
vehicle_year_group = {
    1: "1900-1950",
    2: "1951-1960",
    3: "1961-1970",
    4: "1971-1980",
    5: "1981-1990",
    6: "1991-2000",
    7: "2001-2010",
    8: "2011-2020",
    9: "2021+",
}
stwd_vehicle_type = {
    1: "Passenger Car/Station Wagon",
    2: "Passenger Car with Trailer",
    3: "Motorcycle/Scooter",
    4: "Pickup or Panel Truck",
    5: "Pickup or Panel Truck with Trailer",
    6: "Truck or Truck Tractor",
    7: "Truck or Truck Tractor with Trailer",
    8: "Schoolbus",
    9: "Other Bus",
    10: "Emergency Vehicle",
    11: "Highway Construction Equipment",
    12: "Bicycle",
    13: "Other Vehicle",
    14: "Pedestrian",
    15: "Moped",
    0: "Not Stated",
}
chp_veh_type_towing = {
    1: "Passenger Car, Station Wagon, or Jeep",
    2: "Motorcycle",
    3: "Motor-Driven Cycle < 15 hp",
    4: "Bicycle",
    5: "Motorized Bicycle",
    6: "All-Terrain Vehicle - ATV",
    7: "Sport Utility Vehicle",
    8: "Minivan",
    9: "Paratransit Bus",
    10: "Tour Bus",
    11: "Other Commercial Bus",
    12: "Non-Commercial Bus",
    13: "Schoolbus Public I",
    14: "Schoolbus Public II",
    15: "Schoolbus Private I",
    16: "Schoolbus Private II",
    17: "Schoolbus Contractual I",
    18: "Schoolbus Contractual II",
    19: "General Public Paratransit Vehicle",
    20: "Public Transit Authority",
    21: "Two-Axle Tank Truck",
    22: "Pickup or Panel Truck",
    23: "Pickup Truck With Camper",
    24: "Three-Axle Tank Truck",
    25: "Truck Tractor",
    26: "Two-Axle Truck",
    27: "Three-Axle Truck",
    28: "Semi-Tank Trailer",
    29: "Pull-Tank Trailer",
    30: "Two-Tank Trailer",
    31: "Semi-Trailer",
    32: "Pull Trailer - includes dolly",
    33: "Two Trailers - includes semi and trailer",
    34: "Boat Trailer",
    35: "Utility Trailer",
    36: "Trailer Coach",
    37: "Oversize Vehicle/Load",
    38: "Pole, Pipe, or Logging Dolly",
    39: "Three Trailers - includes semi and two trailers",
    40: "Semi 48 or Less with King Pin to Trailer Axle of over 38",
    41: "Ambulance",
    42: "Dune Buggy",
    43: "Fire Truck - not rescue",
    44: "Forklift",
    45: "Highway Construction Equipment - only while not in construction area",
    46: "Implement of Husbandry",
    47: "Motor Home (40 ft or less)",
    48: "CHP, Police, or Sheriff Car - emergency service or not",
    49: "CHP, Police, or Sheriff Motorcycle - emergency service or not",
    50: "Mobile Equipment",
    51: "Farm Labor Vehicle - certified",
    52: "Federally Legal Double Cargo Combo over 75 ft",
    53: "5th Wheel Trailer",
    54: "Container Chassis",
    55: "Two-Axle Tow Truck",
    56: "Three-Axle Tow Truck",
    57: "Farm Labor Vehicle (non-certified)",
    58: "Farm Labor Transporter",
    59: "Motorhome - over 40 ft",
    60: "Pedestrian (includes motorized wheelchair)",
    61: "School Pupil Activity Bus I (<2002)",
    62: "School Pupil Activity Bus II (<2002)",
    63: "Youth Bus",
    64: "School Pupil Activity Bus I",
    65: "School Pupil Activity Bus II",
    66: "School Bus Without Pupil Passengers",
    71: "Passenger Car - Hazardous Materials Only",
    72: "Pickups and Panels - Hazardous Materials Only",
    73: "Pickups and Campers - Hazardous Materials Only",
    75: "Truck Tractor - Hazardous Materials Only",
    76: "Two-Axle Truck - Hazardous Materials Only",
    77: "Three or More Axle Truck - Hazardous Materials Only",
    78: "Two-Axle Tank Truck - Hazardous Materials Only",
    79: "Three-Axle Tank Truck - Hazardous Materials Only",
    81: "Passenger Car - Hazardous Waste or Waste/Material Combo",
    82: "Pickups and Panels - Hazardous Waste or Waste/Material Combo",
    83: "Pickups and Campers - Hazardous Waste or Waste/Material Combo",
    85: "Truck Tractor - Hazardous Waste or Waste/Material Combo",
    86: "Two-Axle Truck - Hazardous Waste or Waste/Material Combo",
    87: "Three or More Axle Truck - Hazardous Waste or Waste/Material Combo",
    88: "Two-Axle Tank Truck - Hazardous Waste or Waste/Material Combo",
    89: "Three-Axle Tank Truck - Hazardous Waste or Waste/Material Combo",
    91: "Electric Bicycle",
    93: "Electrically Motorized Board",
    94: "Motorized Transportation Device",
    95: "Miscellaneous Non-Motorized Vehicle With Victim",
    96: "Miscellaneous Motorized Vehicle",
    97: "Low Speed Vehicle",
    98: "Emergency Vehicle on an Emergency Run",
    99: "Not Stated or Unknown - Hit and Run",
}
chp_veh_type_towed = {
    1: "Passenger Car, Station Wagon, or Jeep",
    2: "Motorcycle",
    3: "Motor-Driven Cycle < 15 hp",
    4: "Bicycle",
    5: "Motorized Bicycle",
    6: "All-Terrain Vehicle - ATV",
    7: "Sport Utility Vehicle",
    8: "Minivan",
    9: "Paratransit Bus",
    10: "Tour Bus",
    11: "Other Commercial Bus",
    12: "Non-Commercial Bus",
    13: "Schoolbus Public I",
    14: "Schoolbus Public II",
    15: "Schoolbus Private I",
    16: "Schoolbus Private II",
    17: "Schoolbus Contractual I",
    18: "Schoolbus Contractual II",
    19: "General Public Paratransit Vehicle",
    20: "Public Transit Authority",
    21: "Two-Axle Tank Truck",
    22: "Pickup or Panel Truck",
    23: "Pickup Truck With Camper",
    24: "Three-Axle Tank Truck",
    25: "Truck Tractor",
    26: "Two-Axle Truck",
    27: "Three-Axle Truck",
    28: "Semi-Tank Trailer",
    29: "Pull-Tank Trailer",
    30: "Two-Tank Trailer",
    31: "Semi-Trailer",
    32: "Pull Trailer - includes dolly",
    33: "Two Trailers - includes semi and trailer",
    34: "Boat Trailer",
    35: "Utility Trailer",
    36: "Trailer Coach",
    37: "Oversize Vehicle/Load",
    38: "Pole, Pipe, or Logging Dolly",
    39: "Three Trailers - includes semi and two trailers",
    40: "Semi 48 or Less with King Pin to Trailer Axle of over 38",
    41: "Ambulance",
    42: "Dune Buggy",
    43: "Fire Truck - not rescue",
    44: "Forklift",
    45: "Highway Construction Equipment - only while not in construction area",
    46: "Implement of Husbandry",
    47: "Motor Home (40 ft or less)",
    48: "CHP, Police, or Sheriff Car - emergency service or not",
    49: "CHP, Police, or Sheriff Motorcycle - emergency service or not",
    50: "Mobile Equipment",
    51: "Farm Labor Vehicle - certified",
    52: "Federally Legal Double Cargo Combo over 75 ft",
    53: "5th Wheel Trailer",
    54: "Container Chassis",
    55: "Two-Axle Tow Truck",
    56: "Three-Axle Tow Truck",
    57: "Farm Labor Vehicle (non-certified)",
    58: "Farm Labor Transporter",
    59: "Motorhome - over 40 ft",
    60: "Pedestrian (includes motorized wheelchair)",
    61: "School Pupil Activity Bus I (<2002)",
    62: "School Pupil Activity Bus II (<2002)",
    63: "Youth Bus",
    64: "School Pupil Activity Bus I",
    65: "School Pupil Activity Bus II",
    66: "School Bus Without Pupil Passengers",
    71: "Passenger Car - Hazardous Materials Only",
    72: "Pickups and Panels - Hazardous Materials Only",
    73: "Pickups and Campers - Hazardous Materials Only",
    75: "Truck Tractor - Hazardous Materials Only",
    76: "Two-Axle Truck - Hazardous Materials Only",
    77: "Three or More Axle Truck - Hazardous Materials Only",
    78: "Two-Axle Tank Truck - Hazardous Materials Only",
    79: "Three-Axle Tank Truck - Hazardous Materials Only",
    81: "Passenger Car - Hazardous Waste or Waste/Material Combo",
    82: "Pickups and Panels - Hazardous Waste or Waste/Material Combo",
    83: "Pickups and Campers - Hazardous Waste or Waste/Material Combo",
    85: "Truck Tractor - Hazardous Waste or Waste/Material Combo",
    86: "Two-Axle Truck - Hazardous Waste or Waste/Material Combo",
    87: "Three or More Axle Truck - Hazardous Waste or Waste/Material Combo",
    88: "Two-Axle Tank Truck - Hazardous Waste or Waste/Material Combo",
    89: "Three-Axle Tank Truck - Hazardous Waste or Waste/Material Combo",
    91: "Electric Bicycle",
    93: "Electrically Motorized Board",
    94: "Motorized Transportation Device",
    95: "Miscellaneous Non-Motorized Vehicle With Victim",
    96: "Miscellaneous Motorized Vehicle",
    97: "Low Speed Vehicle",
    98: "Emergency Vehicle on an Emergency Run",
    99: "Not Stated or Unknown - Hit and Run",
}
special_info_f = {1: "75 ft Motor Truck Combo", 0: "Not Stated"}
special_info_g = {1: "32 ft trailer combo", 0: "Not Stated"}
victim_role = {
    1: "Driver",
    2: "Passenger",
    3: "Pedestrian",
    4: "Bicyclist",
    5: "Other",
    0: "Non-Injured Party",
}
victim_sex = {1: "Male", 2: "Female", 3: "Nonbinary", 0: "Not Stated"}
victim_age = {998: "Not Stated", 999: "Fatal Fetus"}
victim_age_group = {
    0: "Unknown",
    1: "0-10",
    2: "11-18",
    3: "19-25",
    4: "26-35",
    5: "36-45",
    6: "46-55",
    7: "56-65",
    8: "66-80",
    9: "81-100",
    10: "100+",
}
victim_degree_of_injury = {
    9: "Not Stated",
    0: "No Injury",
    1: "Complaint of Pain",
    2: "Possible Injury",
    3: "Suspected Minor Injury",
    4: "Other Visible Injury",
    5: "Suspected Serious Injury",
    6: "Severe Injury",
    7: "Killed",
}
victim_degree_of_injury_bin = {0: "Minor or Pain", 1: "Severe or Fatal"}
victim_seating_position = {
    1: "Driver",
    2: "Passenger 1",
    3: "Passenger 2",
    4: "Passenger 3",
    5: "Passenger 4",
    6: "Passenger 5",
    7: "Station Wagon Rear",
    8: "Rear Occupant of Truck or Van",
    9: "Position Unknown",
    0: "Other Occupants",
    10: "Bus Occupant A",
    11: "Bus Occupant B",
    12: "Bus Occupant C",
    13: "Bus Occupant D",
    14: "Bus Occupant E",
    15: "Bus Occupant F",
    16: "Bus Occupant G",
    17: "Bus Occupant H",
    18: "Bus Occupant I",
    19: "Bus Occupant J",
    20: "Bus Occupant K",
    21: "Bus Occupant L",
    22: "Bus Occupant M",
    23: "Bus Occupant N",
    24: "Bus Occupant O",
    25: "Bus Occupant P",
    26: "Bus Occupant Q",
    27: "Bus Occupant R",
    28: "Bus Occupant S",
    29: "Bus Occupant T",
    30: "Bus Occupant U",
    31: "Bus Occupant V",
    32: "Bus Occupant W",
    33: "Bus Occupant X",
    34: "Bus Occupant Y",
    35: "Bus Occupant Z",
    99: "Not Stated",
}
victim_safety_eq_1 = {
    1: "None in Vehicle",
    2: "Unknown",
    3: "Lap Belt Used",
    4: "Lap Belt Not Used",
    5: "Shoulder Harness Used",
    6: "Shoulder Harness Not Used",
    7: "Lap/Shoulder Harness Used",
    8: "Lap/Shoulder Harness Not Used",
    9: "Passive Restraint Used",
    10: "Passive Restraint Not Used",
    11: "Air Bag Deployed",
    12: "Air Bag Not Deployed",
    13: "Other",
    14: "Not Required",
    15: "Child Restraint in Vehicle Used",
    16: "Child Restraint in Vehicle Not Used",
    17: "Child Restraint in Vehicle, Use Unknown",
    18: "Child Restraint in Vehicle, Improper Use",
    19: "No Child Restraint in Vehicle",
    20: "Driver, Motorcycle Helmet Not Used",
    21: "Driver, Motorcycle Helmet Used",
    22: "Passenger, Motorcycle Helmet Not Used",
    23: "Passenger, Motorcycle Helmet Used",
    0: "Not Stated",
}
victim_safety_eq_2 = {
    1: "None in Vehicle",
    2: "Unknown",
    3: "Lap Belt Used",
    4: "Lap Belt Not Used",
    5: "Shoulder Harness Used",
    6: "Shoulder Harness Not Used",
    7: "Lap/Shoulder Harness Used",
    8: "Lap/Shoulder Harness Not Used",
    9: "Passive Restraint Used",
    10: "Passive Restraint Not Used",
    11: "Air Bag Deployed",
    12: "Air Bag Not Deployed",
    13: "Other",
    14: "Not Required",
    15: "Child Restraint in Vehicle Used",
    16: "Child Restraint in Vehicle Not Used",
    17: "Child Restraint in Vehicle, Use Unknown",
    18: "Child Restraint in Vehicle, Improper Use",
    19: "No Child Restraint in Vehicle",
    20: "Driver, Motorcycle Helmet Not Used",
    21: "Driver, Motorcycle Helmet Used",
    22: "Passenger, Motorcycle Helmet Not Used",
    23: "Passenger, Motorcycle Helmet Used",
    0: "Not Stated",
}
victim_ejected = {
    0: "Not Ejected",
    1: "Fully Ejected",
    2: "Partially Ejected",
    3: "Unknown",
    9: "Not Stated",
}
road_cat = {1: "Primary", 2: "Secondary", 3: "Local"}
